
CUTEWIDGETS_ROOT            = $$PWD/..
CUTEWIDGETS_OUTPUT_LIB      = $$CUTEWIDGETS_ROOT/lib

include($$CUTEWIDGETS_ROOT/cutewidgetsfunctions.pri)

TEMPLATE     = app

DESTDIR      = $$CUTEWIDGETS_ROOT/bin

INCLUDEPATH += $$CUTEWIDGETS_ROOT/include
DEPENDPATH += $$CUTEWIDGETS_OUTPUT_LIB

cuteWidgetsAddLibrary($$CUTEWIDGETS_OUTPUT_LIB, cutewidgets)
